### ISSUE TITLE
Pop-up doesn't show if there are any events in non-journal pages

### ISSUE THREAD

**Issue by weaselshit** [hkgnp/logseq-calview-plugin#10]
Hi!

I have some templates for events planned for a day that contain blocks with `start-time` and `end-time` properties. 
Since update to 2.0, the calendar pop-up won't show up, unless I remove those templates. I mentioned that problem in #9 , but since I was able to confirm it to be unrelated, I've created a new issue.

Here is the an example of an error from a developer console:
```
Uncaught (in promise) Error: No page found
    at dA (index-a40ab97e.js:102:168)
    at async Object.show (index-a40ab97e.js:102:905)
dA	@	index-a40ab97e.js:102
await in dA (async)		
(anonymous)	@	index-a40ab97e.js:28
```

Here is (as far as I understand) relevant code:
```
        const o = await logseq.Editor.getPage(i[0].page.id);
        if (!o || !o.journalDay)
            throw new Error("No page found");
```

It seems to me, although I'm not sure I'm getting it right, that the logic here might be flawed. Instead of skipping non-journal pagesm the code throws an error when it encounters one. Am I missing something? Is it intentional?

**Comment by benjypng** [comment]
v2.0.1 should fix this issue.
